// netlify/functions/stylize.ts
import type { Handler } from "@netlify/functions";
import { GoogleGenAI, Modality } from "@google/genai";

// Helper function to fetch an image and convert it to base64
const imageUrlToBase64 = async (url: string): Promise<{ base64: string, mimeType: string }> => {
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`Failed to fetch image: ${response.status} ${response.statusText}`);
  }
  const blob = await response.blob();
  if (blob.type === 'image/png' && blob.size < 20000) {
      throw new Error("404: No Street View imagery available for this location.");
  }
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onloadend = () => {
        const result = reader.result as string;
        resolve({
            base64: result.split(',')[1],
            mimeType: blob.type
        });
    };
    reader.onerror = reject;
    reader.readAsDataURL(blob);
  });
};

const handler: Handler = async (event) => {
  if (event.httpMethod !== 'POST') {
    return { statusCode: 405, body: 'Method Not Allowed' };
  }

  // Get the key securely from Netlify's environment
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    return { statusCode: 500, body: JSON.stringify({ error: "GEMINI_API_KEY is not set" }) };
  }

  try {
    const { streetViewUrl, artStyle } = JSON.parse(event.body || '{}');
    if (!streetViewUrl || !artStyle) {
      return { statusCode: 400, body: JSON.stringify({ error: "Missing streetViewUrl or artStyle" }) };
    }
    
    const ai = new GoogleGenAI({ apiKey });
    const { base64: base64Image, mimeType } = await imageUrlToBase64(streetViewUrl);

    let styleDescription = '';
    switch (artStyle) {
      case 'Oil Painting':
        styleDescription = 'transform the result into a rich and textured oil painting. The style should feature visible, impasto brushstrokes and a deep color palette.';
        break;
      case 'Pencil Sketch':
        styleDescription = 'transform the result into a detailed pencil sketch. The style should be monochromatic, emphasizing lines, shading, and texture to create a hand-drawn, artistic feel.';
        break;
      default:
        styleDescription = 'transform the result into a vibrant and artistic watercolor painting. The style should be loose and expressive, with visible brushstrokes and color bleeds, typical of a real watercolor painting.';
        break;
    }

    const prompt = `
      Analyze the provided street view image of a property.
      First, digitally remove all transient Street View objects 
      specifacally people, moving or parked cars, bicycles, and garbage cans to create a clean, timeless,
      architectural front-on view of the property and its immediate, natural surroundings (trees, sky, lawn) that fade to white. 
      Do not remove aesthetic features: flag poles, fences, trees or bushes, and don't add any that aren't present.
      After cleaning the image, ${styleDescription} Ensure the final output is only the generated image itself, with no text or borders.
    `;

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          { inlineData: { data: base64Image, mimeType: mimeType } },
          { text: prompt },
        ],
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        const base64ImageBytes: string = part.inlineData.data;
        const generatedMimeType = part.inlineData.mimeType;
        const generatedUrl = `data:${generatedMimeType};base64,${base64ImageBytes}`;
        return {
          statusCode: 200,
          body: JSON.stringify({ generatedUrl: generatedUrl }),
        };
      }
    }
    
    throw new Error("No image was generated by the API.");

  } catch (error) {
    console.error("Error in stylize function:", error);
    return {
      statusCode: 500,
      body: JSON.stringify({ error: error instanceof Error ? error.message : "Unknown server error" }),
    };
  }
};

export { handler };