// netlify/functions/stylize-run-background.ts
import { GoogleGenAI, Modality } from "@google/genai";
import { getStore } from "@netlify/blobs"; 
import type { Context } from "@netlify/functions"; 

// ... (imageUrlToBase64 function is unchanged) ...
const imageUrlToBase64 = async (url: string): Promise<{ base64: string, mimeType: string }> => {
  const response = await fetch(url);
  if (!response.ok) { throw new Error(`Failed to fetch image: ${response.status}`); }
  const blob = await response.blob();
  if (blob.type === 'image/png' && blob.size < 20000) {
    throw new Error("404: No Street View imagery available.");
  }
  const arrayBuffer = await blob.arrayBuffer();
  const buffer = Buffer.from(arrayBuffer);
  const base64 = buffer.toString('base64');
  return { base64: base64, mimeType: blob.type };
};


export default async (request: Request, context: Context) => {
  if (request.method !== 'POST') {
    return new Response("Method Not Allowed", { status: 405 });
  }

  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    console.error("[stylize-run] GEMINI_API_KEY is not set");
    return new Response(JSON.stringify({ error: "GEMINI_API_KEY is not set" }), { status: 500 });
  }

  let jobId: string | null = null;
  
  try {
    const { streetViewUrl, artStyle, jobId: reqJobId } = await request.json();
    jobId = reqJobId; 

    if (!streetViewUrl || !artStyle || !jobId) {
      return new Response(JSON.stringify({ error: "Missing streetViewUrl, artStyle, or jobId" }), { status: 400 });
    }
    
    const ai = new GoogleGenAI({ apiKey });
    const { base64: base64Image, mimeType } = await imageUrlToBase64(streetViewUrl);

    // Your prompt
    let styleDescription = '';
    switch (artStyle) {
      case 'Oil Painting':
        styleDescription = 'transform the result into a rich and textured oil painting...';
        break;
      case 'Pencil Sketch':
        styleDescription = 'transform the result into a detailed pencil sketch...';
        break;
      default:
        styleDescription = 'transform the result into a vibrant and artistic watercolor painting...';
        break;
    }

    // === UPDATED === Added instruction for aspect ratio
    const prompt = `Analyze the provided street view image, remove parked and moving cars trucks and vehicles, pedestrians, and garbage cans and reproduce in ${styleDescription} with no text or borders. Do not remove trees, fences, or architectural features, and do not add objects. Fade gently to white at the edges for an artistic look. The final output image must have a 4:3 aspect ratio.`;

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: { parts: [{ inlineData: { data: base64Image, mimeType } }, { text: prompt }] },
      config: { responseModalities: [Modality.IMAGE] },
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        const generatedUrl = `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
        
        const store = getStore("stylized-images");
        await store.setJSON(jobId, {
          status: "complete",
          generatedUrl: generatedUrl
        });
        
        return new Response("Job complete.", { status: 200 });
      }
    }
    
    throw new Error("No image was generated by the API.");

  } catch (error) {
    console.error("Error in stylize-run function:", error);
    
    let errorMessage = error instanceof Error ? error.message : "Unknown server error";
    if (errorMessage.startsWith("404:")) {
        errorMessage = "We couldn't find Street View imagery for that address. Please try a nearby address or intersection.";
    }

    if (jobId) {
      try {
        const store = getStore("stylized-images");
        await store.setJSON(jobId, {
          status: "error",
          message: errorMessage 
        });
      } catch (storeError) {
        console.error("Failed to even write error to blob store:", storeError);
      }
    }
    return new Response(JSON.stringify({ error: errorMessage }), { status: 500 });
  }
};